/** @type {import('ts-jest').JestConfigWithTsJest} */
module.exports = {
  preset: "ts-jest",
  testEnvironment: "node",
  modulePaths: ['node_modules', '<rootDir>'],
  // Without this, jest picks up the .d.ts files generated by the build in dist/
  // and counts them as empty test suites.
  testPathIgnorePatterns: ['/node_modules/', '/dist/'],
  // uuid 14 is pure ESM (no "require" export), which jest cannot load as
  // CommonJS. So we remove it from the ignored modules and transpile it.
  transform: {
    '^.+\\.[tj]sx?$': ['ts-jest', { tsconfig: { allowJs: true } }]
  },
  transformIgnorePatterns: ['/node_modules/(?!uuid)']
};
